version: "3"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ".:/usr/src/app"
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "db_volume:/var/lib/postgresql/data"
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "3001:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
volumes:
  db_volume:
