name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/vlang/v
      - run: make
        working-directory: ~/v
      - run: ~/v/v main.v
